# Generated by Django 5.0 on 2024-01-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="default.user.png",
                null=True,
                upload_to="images/profile",
            ),
        ),
    ]
