# Generated by Django 5.0 on 2024-01-04 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("discount_percentage", models.IntegerField()),
                ("max_usage", models.IntegerField()),
                ("current_usage", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="coupon_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Shop.coupon",
            ),
        ),
    ]
