# Generated by Django 5.0 on 2024-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Shop", "0002_coupon_product_discount_price_product_coupon_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_product",
            field=models.BooleanField(default=False),
        ),
    ]
