# Generated by Django 5.0 on 2024-01-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Order", "0001_initial"),
        ("Shop", "0004_rename_discount_price_product_old_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_product_name",
                to="Shop.product",
            ),
        ),
    ]
