# Generated by Django 5.0 on 2024-01-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Order", "0002_alter_cart_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
