# Generated by Django 5.0 on 2024-01-08 05:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Order", "0003_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="status",
            new_name="full_payment_data",
        ),
    ]
